### ISSUE TITLE
按照你说的，把“kindeditor”文件夹放到“\vendor\pjkui\”文件夹下，还是出错！！

### ISSUE THREAD

**Issue by shcysy** [pjkui/kindeditor#1]
把“kindeditor”文件夹放到“\vendor\pjkui\”文件夹下，然后在视图中“echo $form->field($model, 'rememberMe')->widget('pjkui\kindeditor\KindEditor',[]);”，结果提示“Class 'pjkui\kindeditor\KindEditor' not found”，
首先，文档里说安装，必须得安装吗？？？我用的是yii2的归档版本，应该怎么安装？？？

**Comment by pjkui** [comment]
其实建议用compaser,这个是比较方便和规范的安装方法，如果是拷贝的话，应该有一个文件需要修改，以保证这个kindeditor类被加载。
这个文件是`/vendor/composer/autoload_psr4.php`.添加一行
`'pjkui\\kindeditor\\'=>array($vendorDir . '/pjkui/kindeditor'),`
