### ISSUE TITLE
上传图片总是失败

### ISSUE THREAD

**Issue by andyRon** [pjkui/kindeditor#3]
view中： 
        echo $form->field($model, 'content')->widget('pjkui\kindeditor\KindEditor',[
               'clientOptions' => [
               'allowUpload'=>'true',
               'uploadJson' => '/media/index/upload',
              ]
         ]);

form表单也是这个上传地址：
       `<form class="ke-upload-area ke-form" method="post" enctype="multipart/form-data" target="kindeditor_upload_iframe_1446532148134" action="/media/index/upload?dir=image"><div class="ke-dialog-row">`

总是提示400报错

**Comment by pjkui** [comment]
action="/media/index/upload?dir=image 这个路由地址 应该不对。长传地址 他会自动命名为Kuplaod。如果没有记错。404错误就验证了路由不对的猜测

**Comment by andyRon** [comment]
问题解决了，是yii2的问题，因为YII2的防止csrf攻击，不能多次提交相同的表单。在当前提交的表单controller中添加

```
      public $enableCsrfValidation = false;
```

就好了。

**Comment by pjkui** [comment]
well done!

**Comment by pjkui** [comment]
这个倒是提醒了我，应该是我的程序也有不完善的地方，在生成表单的地方加一个csrf码就行了，这样就不需要关闭csrf验证了——关闭更新会降低用户网站安全性，我会尽快做出这个版本的更新。如果你做了，可以提交pull request。
