### ISSUE TITLE
你好，yii2用了编辑器后，有提示内容，还是会提示内容不能为空，这要怎么解决啊？

### ISSUE THREAD

**Issue by asialong** [pjkui/kindeditor#4]
你好 pjkui，yii2用了你家编辑器后，有提示内容，还是会提示内容不能为空，这要怎么解决啊？

**Comment by pjkui** [comment]
提示内容不能为空，需要去检查一下该表对应的Model的设置，如果这个字段是required。那么就不能为空。如果数据库该表对应的此字段为Not null.那么也不能为空。因为此编辑器不涉及数据库的校验的逻辑，所以请检查一下数据库和model层的代码。
如果有什么好的开发建议，欢迎随时反馈！

**Comment by asialong** [comment]
是的啊，问题是我有在编辑里填写内容啊，但是提交的时候还是提示不能为空

**Comment by asialong** [comment]
突然发现一个问题，是这样，不管填什么，新建记录的时候，第一次提交会提示不能为空，再点一次提交就可以了，这真是奇怪，如果在不用编辑器的情况下是OK的，所以感觉是编辑器哪个地方要弄一下

**Comment by pjkui** [comment]
这个，你看看是什么字段？一般来说不会的，因为没有注入js代码，保持了官方的完整性。你截个出错时候的图，看看是哪个字段？这个字段是什么类型的？比如是int，text，还是其他？因为其他人用了并没有出现这个情况，我以前测的时候也没有出现这个情况

**Comment by asialong** [comment]
字段是 text类型的，感觉是编辑器那边有点问题，因为填了内容，第一次提交前，编辑器没有把内容传给form里的那个字段，当第一次点提交的时候，他才做这个动作，所以在第二次点提交的时候，就有内容了

**Comment by pjkui** [comment]
text类型， 你用了编辑器的那种功能呢？是textArea. 上传文件？上传图片？还是没有用到本编辑器的功能，只是一个text。

**Comment by asialong** [comment]
现在是 textArea，等这个调通了，再调上传单图和多图的功能

**Comment by pjkui** [comment]
你在服务器端 直接打印出来提交的信息，看看第一次post了textArea没？不要做任何的校验。

``` php
print_r($_POST);
```

**Comment by asialong** [comment]
不做校验，第一次 post有 接收到值

**Comment by pjkui** [comment]
那就是你的上层逻辑有问题了

**Comment by asialong** [comment]
上层逻辑？

**Comment by asialong** [comment]
会不会和  use kartik\widgets\ActiveForm;  这个第三方的有关系？

**Comment by pjkui** [comment]
关闭表单的_csrf 验证试试

**Comment by pjkui** [comment]
如果都提交了同一个表单，那么可能会造成冲突，然后没有数据传上去

**Comment by asialong** [comment]
用 public $enableCsrfValidation = false;  这个在控制器里关闭了，还是一样

**Comment by pjkui** [comment]
如果$_POST有内容，问题就不是我做的这个编辑器的问题了，希望你好好检查一下代码。

**Comment by asialong** [comment]
那我再去研究下，谢了
