### ISSUE TITLE
提个修改意见

### ISSUE THREAD

**Issue by lizishushu** [pjkui/kindeditor#5]
在KindEditorAction文件中，指定了8个参数，分别是 ：$config;$php_path;$php_url;$root_path;$root_url;$save_path;$save_url;$max_size;
 这些参数目前您已经写在了初始化函数中，而且写死了，开发者很难修改。为了方便开发者对这些参数自定义，建议把初始化函数中的方法进项稍微修改，
比如定义save_url方法时可以：`$this->save_url= $this->save_url?$this->save_url:$this->php_url . 'upload/';`
这样的话，开发者在编写的时候，就可以在代码中这样直接定义：`    			'Kupload' => [
    					'class' => 'pjkui\kindeditor\KindEditorAction',
    					'save_path'=>"/app/imgs",
    					'save_url'=>'http://imgs.test.dev/'
    			]`

**Comment by pjkui** [comment]
此功能已经在新版本的已经被 @f2h2h1实现。
